---
- name: Add Argo Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm
- name: Create argocd namespace
  kubernetes.core.k8s:
    state: present
    definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: argocd
- name: Deploy ArgoCD chart inside argocd namespace
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    values_files:
      - values/values.yaml
